# Generated by Django 3.2 on 2024-02-07 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'default_related_name': 'recipeingredient', 'verbose_name': 'рецепт и ингредиент', 'verbose_name_plural': 'рецепты и ингредиенты'},
        ),
        migrations.RemoveConstraint(
            model_name='favorites',
            name='unique_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_cart',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не может равняться нулю'), django.core.validators.MaxValueValidator(32767, message='Больше суток готовится только дипломный проект')], verbose_name='время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество для ингредиента не может быть меньше 1'), django.core.validators.MaxValueValidator(32767, message='Количество для ингредиента не может быть больше 10000')], verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('consumer', 'recipe'), name='favorites prevent double add'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('consumer', 'recipe'), name='shoppingcart prevent double add'),
        ),
    ]
