# Generated by Django 3.2 on 2024-02-08 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240207_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=200, verbose_name='Мера измерения'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество для ингредиента не может быть меньше 1'), django.core.validators.MaxValueValidator(32767, message='Количество для ингредиента не может быть больше 32767')], verbose_name='количество'),
        ),
    ]
