# Generated by Django 3.2 on 2024-02-09 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Введите корректное количество для ингредиента'), django.core.validators.MaxValueValidator(32767, message='Введите корректное количество для ингредиента')], verbose_name='количество'),
        ),
    ]
