# Generated by Django 3.2 on 2024-01-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_in_black_list',
            field=models.BooleanField(default=False, verbose_name='В черном списке'),
        ),
    ]
